# Generated by Django 4.0.3 on 2022-04-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_tag_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
